artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/GuruChandra/DataSet/raw/refs/heads/main/titanic.zip
  local_data_file: artifacts/data_ingestion/titanic.zip
  unzip_dir: artifacts/data_ingestion